
name: proyecto_clinicas
version: '1.0.0'
config-version: 2

profile: proyecto_clinicas

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  proyecto_clinicas:

    staging:
      +materialized: view
      +schema: staging
      +database: lfr_silver
      +tags:
        - staging

    silver:
      +materialized: table     
      +schema: silver
      +database: lfr_silver
      +tags:
        - silver